# Generated by Django 4.2.1 on 2023-06-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_income_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='description',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='expensecategory',
            old_name='description',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='description',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='incomecategory',
            old_name='description',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
    ]
