# Generated by Django 4.2.1 on 2023-06-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_description_expense_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.expenseaccount'),
            preserve_default=False,
        ),
    ]
